package com.sanluan.entities.log;

// Generated 2015-2-3 14:44:33 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * LogTicket generated by hbm2java
 */
@Entity
@Table(name = "log_ticket")
public class LogTicket implements java.io.Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private int ticketId;
	private int userId;
	private int remainder;
	private int used;
	private Date createDate;

	public LogTicket() {
	}

	public LogTicket(int ticketId, int userId, int remainder, int used, Date createDate) {
		this.ticketId = ticketId;
		this.userId = userId;
		this.remainder = remainder;
		this.used = used;
		this.createDate = createDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "ticket_id", nullable = false)
	public int getTicketId() {
		return this.ticketId;
	}

	public void setTicketId(int ticketId) {
		this.ticketId = ticketId;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "remainder", nullable = false)
	public int getRemainder() {
		return this.remainder;
	}

	public void setRemainder(int remainder) {
		this.remainder = remainder;
	}

	@Column(name = "used", nullable = false)
	public int getUsed() {
		return this.used;
	}

	public void setUsed(int used) {
		this.used = used;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", nullable = false, length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
