package com.sanluan.cms.entities.log;

// Generated 2015-2-3 14:44:33 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LogPassword generated by hbm2java
 */
@Entity
@Table(name = "log_password")
public class LogPassword implements java.io.Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Integer userId;
	private String ip;
	private Date createDate;
	private String oldPassword;
	private String newPassword;

	public LogPassword() {
	}

	public LogPassword(String ip, Date createDate, String newPassword) {
		this.ip = ip;
		this.createDate = createDate;
		this.newPassword = newPassword;
	}

	public LogPassword(Integer userId, String ip, Date createDate, String oldPassword, String newPassword) {
		this.userId = userId;
		this.ip = ip;
		this.createDate = createDate;
		this.oldPassword = oldPassword;
		this.newPassword = newPassword;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "user_id")
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "ip", nullable = false, length = 20)
	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", nullable = false, length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "old_password", length = 100)
	public String getOldPassword() {
		return this.oldPassword;
	}

	public void setOldPassword(String oldPassword) {
		this.oldPassword = oldPassword;
	}

	@Column(name = "new_password", nullable = false, length = 100)
	public String getNewPassword() {
		return this.newPassword;
	}

	public void setNewPassword(String newPassword) {
		this.newPassword = newPassword;
	}

}
