package com.sanluan.cms.entities.cms;

// Generated 2015-5-6 15:49:39 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

import com.sanluan.common.source.entity.MyColumn;

/**
 * CmsBlock generated by hbm2java
 */
@Entity
@Table(name = "cms_block")
public class CmsBlock implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	@MyColumn(title = "页面", condition = true)
	private Integer pageId;
	@MyColumn(title = "分类", condition = true)
	private Integer categoryId;
	@MyColumn(title = "名称")
	private String name;
	@MyColumn(title = "模板")
	private String template;
	@MyColumn(title = "数据条数")
	private int dataSize;
	@MyColumn(title = "类型", condition = true)
	private int type;
	@MyColumn(title = "描述")
	private String description;

	public CmsBlock() {
	}

	public CmsBlock(String name, int dataSize, int type, String description) {
		this.name = name;
		this.dataSize = dataSize;
		this.type = type;
		this.description = description;
	}

	public CmsBlock(Integer pageId, Integer categoryId, String name, String template, int dataSize, int type, String description) {
		this.pageId = pageId;
		this.categoryId = categoryId;
		this.name = name;
		this.template = template;
		this.dataSize = dataSize;
		this.type = type;
		this.description = description;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "page_id")
	public Integer getPageId() {
		return this.pageId;
	}

	public void setPageId(Integer pageId) {
		this.pageId = pageId;
	}

	@Column(name = "category_id")
	public Integer getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(Integer categoryId) {
		this.categoryId = categoryId;
	}

	@Column(name = "name", nullable = false, length = 200)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "template", length = 65535)
	public String getTemplate() {
		return this.template;
	}

	public void setTemplate(String template) {
		this.template = template;
	}

	@Column(name = "data_size", nullable = false)
	public int getDataSize() {
		return this.dataSize;
	}

	public void setDataSize(int dataSize) {
		this.dataSize = dataSize;
	}

	@Column(name = "type", nullable = false)
	public int getType() {
		return this.type;
	}

	public void setType(int type) {
		this.type = type;
	}

	@Column(name = "description", nullable = false, length = 500)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
