package com.sanluan.cms.entities.cms;

// Generated 2015-5-6 15:49:39 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

import com.sanluan.common.source.entity.MyColumn;

/**
 * CmsModel generated by hbm2java
 */
@Entity
@Table(name = "cms_model")
public class CmsModel implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	@MyColumn(title = "名称")
	private String name;
	@MyColumn(title = "模板路径")
	private String templatePath;
	@MyColumn(title = "模板路径1")
	private String templatePath1;
	@MyColumn(title = "已删除", condition = true)
	private boolean isDisable;

	public CmsModel() {
	}

	public CmsModel(String name, boolean isDisable) {
		this.name = name;
		this.isDisable = isDisable;
	}

	public CmsModel(String name, String templatePath, String templatePath1, boolean isDisable) {
		this.name = name;
		this.templatePath = templatePath;
		this.templatePath1 = templatePath1;
		this.isDisable = isDisable;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 200)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "template_path", length = 200)
	public String getTemplatePath() {
		return this.templatePath;
	}

	public void setTemplatePath(String templatePath) {
		this.templatePath = templatePath;
	}

	@Column(name = "template_path1", length = 200)
	public String getTemplatePath1() {
		return this.templatePath1;
	}

	public void setTemplatePath1(String templatePath1) {
		this.templatePath1 = templatePath1;
	}

	@Column(name = "is_disable", nullable = false)
	public boolean isIsDisable() {
		return this.isDisable;
	}

	public void setIsDisable(boolean isDisable) {
		this.isDisable = isDisable;
	}

}
