package com.sanluan.cms.entities.cms;

// Generated 2015-5-6 15:49:39 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

import com.sanluan.common.source.entity.MyColumn;

/**
 * CmsModelExtend generated by hbm2java
 */
@Entity
@Table(name = "cms_model_extend")
public class CmsModelExtend implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	@MyColumn(title = "模型", condition = true)
	private int modelId;
	@MyColumn(title = "扩展类型", condition = true)
	private int extendType;
	@MyColumn(title = "名称")
	private String name;
	@MyColumn(title = "描述")
	private String description;
	@MyColumn(title = "类型", condition = true)
	private short type;
	@MyColumn(title = "字段")
	private String code;
	@MyColumn(title = "表单类型")
	private int inputType;
	@MyColumn(title = "默认值")
	private String defaultValue;

	public CmsModelExtend() {
	}

	public CmsModelExtend(int modelId, int extendType, String name, short type, String code, int inputType) {
		this.modelId = modelId;
		this.extendType = extendType;
		this.name = name;
		this.type = type;
		this.code = code;
		this.inputType = inputType;
	}

	public CmsModelExtend(int modelId, int extendType, String name, String description, short type, String code, int inputType,
			String defaultValue) {
		this.modelId = modelId;
		this.extendType = extendType;
		this.name = name;
		this.description = description;
		this.type = type;
		this.code = code;
		this.inputType = inputType;
		this.defaultValue = defaultValue;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "model_id", nullable = false)
	public int getModelId() {
		return this.modelId;
	}

	public void setModelId(int modelId) {
		this.modelId = modelId;
	}

	@Column(name = "extend_type", nullable = false)
	public int getExtendType() {
		return this.extendType;
	}

	public void setExtendType(int extendType) {
		this.extendType = extendType;
	}

	@Column(name = "name", nullable = false, length = 200)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", length = 500)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "type", nullable = false)
	public short getType() {
		return this.type;
	}

	public void setType(short type) {
		this.type = type;
	}

	@Column(name = "code", nullable = false, length = 100)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "input_type", nullable = false)
	public int getInputType() {
		return this.inputType;
	}

	public void setInputType(int inputType) {
		this.inputType = inputType;
	}

	@Column(name = "default_value", length = 200)
	public String getDefaultValue() {
		return this.defaultValue;
	}

	public void setDefaultValue(String defaultValue) {
		this.defaultValue = defaultValue;
	}

}
