package com.sanluan.cms.entities.cms;

// Generated 2015-5-6 15:49:39 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

import com.sanluan.common.source.entity.MyColumn;

/**
 * CmsSiteUser generated by hbm2java
 */
@Entity
@Table(name = "cms_site_user")
public class CmsSiteUser implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	@MyColumn(title = "站点", condition = true)
	private int siteId;
	@MyColumn(title = "用户", condition = true)
	private int userId;
	@MyColumn(title = "是否管理员", condition = true)
	private boolean isAdmin;
	@MyColumn(title = "已禁用", condition = true)
	private boolean isDisable;

	public CmsSiteUser() {
	}

	public CmsSiteUser(int siteId, int userId, boolean isAdmin, boolean isDisable) {
		this.siteId = siteId;
		this.userId = userId;
		this.isAdmin = isAdmin;
		this.isDisable = isDisable;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "site_id", nullable = false)
	public int getSiteId() {
		return this.siteId;
	}

	public void setSiteId(int siteId) {
		this.siteId = siteId;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "is_admin", nullable = false)
	public boolean isIsAdmin() {
		return this.isAdmin;
	}

	public void setIsAdmin(boolean isAdmin) {
		this.isAdmin = isAdmin;
	}

	@Column(name = "is_disable", nullable = false)
	public boolean isIsDisable() {
		return this.isDisable;
	}

	public void setIsDisable(boolean isDisable) {
		this.isDisable = isDisable;
	}

}
