package com.sanluan.cms.entities.cms;

// Generated 2015-5-6 15:49:39 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import com.sanluan.common.source.entity.MyColumn;

/**
 * CmsUser generated by hbm2java
 */
@Entity
@Table(name = "cms_user")
public class CmsUser implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int userId;
	@MyColumn(title = "文章数")
	private int contentCount;
	@MyColumn(title = "评论数")
	private int commentCount;

	public CmsUser() {
	}

	public CmsUser(int userId, int contentCount, int commentCount) {
		this.userId = userId;
		this.contentCount = contentCount;
		this.commentCount = commentCount;
	}

	@Id
	@Column(name = "user_id", unique = true, nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "content_count", nullable = false)
	public int getContentCount() {
		return this.contentCount;
	}

	public void setContentCount(int contentCount) {
		this.contentCount = contentCount;
	}

	@Column(name = "comment_count", nullable = false)
	public int getCommentCount() {
		return this.commentCount;
	}

	public void setCommentCount(int commentCount) {
		this.commentCount = commentCount;
	}

}
