package com.sanluan.entities.web;

// Generated 2015-2-28 16:38:56 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * WebContent generated by hbm2java
 */
@Entity
@Table(name = "web_content")
public class WebContent implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private int catalogId;
	private String title;
	private int userId;
	private String content;
	private int status;
	private Date published;
	private Date realPublished;

	public WebContent() {
	}

	public WebContent(int catalogId, String title, int userId, int status, Date published, Date realPublished) {
		this.catalogId = catalogId;
		this.title = title;
		this.userId = userId;
		this.status = status;
		this.published = published;
		this.realPublished = realPublished;
	}

	public WebContent(int catalogId, String title, int userId, String content, int status, Date published, Date realPublished) {
		this.catalogId = catalogId;
		this.title = title;
		this.userId = userId;
		this.content = content;
		this.status = status;
		this.published = published;
		this.realPublished = realPublished;
	}

	public WebContent(Integer id, int catalogId, String title, int userId, int status, Date published, Date realPublished) {
		this.id = id;
		this.catalogId = catalogId;
		this.title = title;
		this.userId = userId;
		this.status = status;
		this.published = published;
		this.realPublished = realPublished;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "catalog_id", nullable = false)
	public int getCatalogId() {
		return this.catalogId;
	}

	public void setCatalogId(int catalogId) {
		this.catalogId = catalogId;
	}

	@Column(name = "title", nullable = false, length = 100)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "content", length = 65535)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "status", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "published", nullable = false, length = 19)
	public Date getPublished() {
		return this.published;
	}

	public void setPublished(Date published) {
		this.published = published;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "real_published", nullable = false, length = 19)
	public Date getRealPublished() {
		return this.realPublished;
	}

	public void setRealPublished(Date realPublished) {
		this.realPublished = realPublished;
	}
}
