package com.sanluan.entities.web;

// Generated 2015-1-27 11:53:39 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * WebPage generated by hbm2java
 */
@Entity
@Table(name = "web_page")
public class WebPage implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private int userPageId;
	private String name;
	private String template;
	private int userId;
	private Date createDate;

	public WebPage() {
	}

	public WebPage(int userPageId, String name, String template, int userId, Date createDate) {
		this.userPageId = userPageId;
		this.name = name;
		this.template = template;
		this.userId = userId;
		this.createDate = createDate;
	}
	
	public WebPage(Integer id , int userPageId, String name, int userId, Date createDate) {
		this.id = id;
		this.userPageId = userPageId;
		this.name = name;
		this.userId = userId;
		this.createDate = createDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "user_page_id", nullable = false)
	public int getUserPageId() {
		return this.userPageId;
	}

	public void setUserPageId(int userPageId) {
		this.userPageId = userPageId;
	}

	@Column(name = "name", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "template", nullable = false, length = 65535)
	public String getTemplate() {
		return this.template;
	}

	public void setTemplate(String template) {
		this.template = template;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", nullable = false, length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
