package com.sanluan.entities.web;

// Generated 2015-2-3 14:44:33 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * WebUserPage generated by hbm2java
 */
@Entity
@Table(name = "web_user_page")
public class WebUserPage implements java.io.Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String name;
	private String template;
	private Date lastUpdateDate;
	private int userId;
	private boolean published;
	private Date createDate;

	public WebUserPage() {
	}

	public WebUserPage(String name, String template, int userId, boolean published, Date createDate) {
		this.name = name;
		this.template = template;
		this.userId = userId;
		this.published = published;
		this.createDate = createDate;
	}

	public WebUserPage(String name, String template, Date lastUpdateDate, int userId, boolean published, Date createDate) {
		this.name = name;
		this.template = template;
		this.lastUpdateDate = lastUpdateDate;
		this.userId = userId;
		this.published = published;
		this.createDate = createDate;
	}
	
	public WebUserPage(Integer id, String name, Date lastUpdateDate, int userId, boolean published, Date createDate) {
		this.id = id;
		this.name = name;
		this.lastUpdateDate = lastUpdateDate;
		this.userId = userId;
		this.published = published;
		this.createDate = createDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "template", nullable = false, length = 65535)
	public String getTemplate() {
		return this.template;
	}

	public void setTemplate(String template) {
		this.template = template;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_update_date", length = 19)
	public Date getLastUpdateDate() {
		return this.lastUpdateDate;
	}

	public void setLastUpdateDate(Date lastUpdateDate) {
		this.lastUpdateDate = lastUpdateDate;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "published", nullable = false)
	public boolean isPublished() {
		return this.published;
	}

	public void setPublished(boolean published) {
		this.published = published;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", nullable = false, length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
