package com.sanluan.entities.system;

// Generated 2015-1-27 11:53:39 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TaskTodo generated by hbm2java
 */
@Entity
@Table(name = "system_task")
public class SystemTask implements java.io.Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String title;
	private int userId;
	private String command;
	private Date createDate;
	private Date timeoutDate;
	private String status;
	private String result;

	public SystemTask() {
	}

	public SystemTask(String title, int userId, String command, Date createDate, Date timeoutDate, String status) {
		this.title = title;
		this.userId = userId;
		this.command = command;
		this.createDate = createDate;
		this.timeoutDate = timeoutDate;
		this.status = status;
	}

	public SystemTask(String title, int userId, String command, Date createDate, Date timeoutDate, String status, String result) {
		this.title = title;
		this.userId = userId;
		this.command = command;
		this.createDate = createDate;
		this.timeoutDate = timeoutDate;
		this.status = status;
		this.result = result;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "title", nullable = false, length = 50)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "command", nullable = false, length = 100)
	public String getCommand() {
		return this.command;
	}

	public void setCommand(String command) {
		this.command = command;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", nullable = false, length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "timeout_date", nullable = false, length = 19)
	public Date getTimeoutDate() {
		return this.timeoutDate;
	}

	public void setTimeoutDate(Date timeoutDate) {
		this.timeoutDate = timeoutDate;
	}

	@Column(name = "status", nullable = false, length = 10)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "result", length = 100)
	public String getResult() {
		return this.result;
	}

	public void setResult(String result) {
		this.result = result;
	}

}
